// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: taskTransport.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// id калькулятора
type CalculatorID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CalculatorID) Reset() {
	*x = CalculatorID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskTransport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatorID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatorID) ProtoMessage() {}

func (x *CalculatorID) ProtoReflect() protoreflect.Message {
	mi := &file_taskTransport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatorID.ProtoReflect.Descriptor instead.
func (*CalculatorID) Descriptor() ([]byte, []int) {
	return file_taskTransport_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatorID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// квитанция о приеме ответа вычислителя
type Receipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskTransport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_taskTransport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_taskTransport_proto_rawDescGZIP(), []int{1}
}

func (x *Receipt) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Сообщение, описывающее передачу от оркестратора к калькулятору
type MessageTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X     float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y     float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Op    string  `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`
	Plus  int64   `protobuf:"varint,5,opt,name=plus,proto3" json:"plus,omitempty"`
	Minus int64   `protobuf:"varint,6,opt,name=minus,proto3" json:"minus,omitempty"`
	Mult  int64   `protobuf:"varint,7,opt,name=mult,proto3" json:"mult,omitempty"`
	Div   int64   `protobuf:"varint,8,opt,name=div,proto3" json:"div,omitempty"`
}

func (x *MessageTask) Reset() {
	*x = MessageTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskTransport_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTask) ProtoMessage() {}

func (x *MessageTask) ProtoReflect() protoreflect.Message {
	mi := &file_taskTransport_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTask.ProtoReflect.Descriptor instead.
func (*MessageTask) Descriptor() ([]byte, []int) {
	return file_taskTransport_proto_rawDescGZIP(), []int{2}
}

func (x *MessageTask) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageTask) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MessageTask) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MessageTask) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *MessageTask) GetPlus() int64 {
	if x != nil {
		return x.Plus
	}
	return 0
}

func (x *MessageTask) GetMinus() int64 {
	if x != nil {
		return x.Minus
	}
	return 0
}

func (x *MessageTask) GetMult() int64 {
	if x != nil {
		return x.Mult
	}
	return 0
}

func (x *MessageTask) GetDiv() int64 {
	if x != nil {
		return x.Div
	}
	return 0
}

// Сообщение, описывающее передачу от калькулятора к оркестратору
type MessageResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result float64 `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	Err    string  `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *MessageResult) Reset() {
	*x = MessageResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskTransport_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResult) ProtoMessage() {}

func (x *MessageResult) ProtoReflect() protoreflect.Message {
	mi := &file_taskTransport_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResult.ProtoReflect.Descriptor instead.
func (*MessageResult) Descriptor() ([]byte, []int) {
	return file_taskTransport_proto_rawDescGZIP(), []int{3}
}

func (x *MessageResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageResult) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *MessageResult) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_taskTransport_proto protoreflect.FileDescriptor

var file_taskTransport_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x22, 0x1e, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22,
	0x99, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6c, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x6c, 0x75, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6d, 0x69, 0x6e, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x75, 0x6c, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x76,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x64, 0x69, 0x76, 0x22, 0x49, 0x0a, 0x0d, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0x95, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x63, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x1b, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x1a, 0x1a,
	0x2e, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x42, 0x0a, 0x0a, 0x53, 0x65,
	0x6e, 0x64, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x76, 0x33,
	0x34, 0x35, 0x39, 0x32, 0x32, 0x2f, 0x61, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x6f, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x5f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_taskTransport_proto_rawDescOnce sync.Once
	file_taskTransport_proto_rawDescData = file_taskTransport_proto_rawDesc
)

func file_taskTransport_proto_rawDescGZIP() []byte {
	file_taskTransport_proto_rawDescOnce.Do(func() {
		file_taskTransport_proto_rawDescData = protoimpl.X.CompressGZIP(file_taskTransport_proto_rawDescData)
	})
	return file_taskTransport_proto_rawDescData
}

var file_taskTransport_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_taskTransport_proto_goTypes = []interface{}{
	(*CalculatorID)(nil),  // 0: taskTransport.CalculatorID
	(*Receipt)(nil),       // 1: taskTransport.Receipt
	(*MessageTask)(nil),   // 2: taskTransport.MessageTask
	(*MessageResult)(nil), // 3: taskTransport.MessageResult
}
var file_taskTransport_proto_depIdxs = []int32{
	0, // 0: taskTransport.CalcService.GetTask:input_type -> taskTransport.CalculatorID
	3, // 1: taskTransport.CalcService.SendAnswer:input_type -> taskTransport.MessageResult
	2, // 2: taskTransport.CalcService.GetTask:output_type -> taskTransport.MessageTask
	1, // 3: taskTransport.CalcService.SendAnswer:output_type -> taskTransport.Receipt
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_taskTransport_proto_init() }
func file_taskTransport_proto_init() {
	if File_taskTransport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_taskTransport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculatorID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskTransport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskTransport_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskTransport_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taskTransport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskTransport_proto_goTypes,
		DependencyIndexes: file_taskTransport_proto_depIdxs,
		MessageInfos:      file_taskTransport_proto_msgTypes,
	}.Build()
	File_taskTransport_proto = out.File
	file_taskTransport_proto_rawDesc = nil
	file_taskTransport_proto_goTypes = nil
	file_taskTransport_proto_depIdxs = nil
}
