POST http://localhost:8000/newexpression HTTP/1.1
content-type: application/json

{
    "expression": "2*(-5)",
  "timings": {
    "plus":   2,
    "minus":  2,
    "mult":   4,
    "div":    4
  }
}

